[package]
name = "bulirsch"
version = "0.1.0"
authors = ["Josh Burkart"]
edition = "2024"
license = "MIT"

[dependencies]
ndarray = { version = "0.16.1" }
num-traits = { version = "0.2.19" }

[dev-dependencies]
approx = { version = "0.5.1" }
ode_solvers = { version = "0.6.1" }
